export enum sidebarMenuItems {
  learn_Html = "learn html",
  learn_css = "learn css",
  essay_on_car = "essay on car",
  learn_js = "learn js",
  learn_reactjs = "learn reactjs",
  axios_post = "axios post",
  navigation_in_nextjs = "navigation in nextjs",
  ssr_in_nextjs = "ssr in nextjs",
  update_record_in_nodejs = "update record in nodejs",
  mongoose_connect = "mongoose connect",
  express_json = "express json",
  learn_Html1 = "learn html",
  learn_css1 = "learn css",
  essay_on_car1 = "essay on car",
  learn_js1 = "learn js",
  learn_reactjs1 = "learn reactjs",
  axios_post1 = "axios post",
  navigation_in_nextjs1 = "navigation in nextjs",
  ssr_in_nextjs1 = "ssr in nextjs",
  update_record_in_nodejs1 = "update record in nodejs",
  mongoose_connect1 = "mongoose connect",
  express_json1 = "express json",
}
